#!/usr/bin/env bash
STATE=""
while :
do
    NEW_STATE=$(acpi | awk -F [\ ,] 'FNR==1 {print $3}')
	if [ "$NEW_STATE" != "$STATE" ]; then
		STATE=$NEW_STATE
		if [ "$STATE" = "Discharging" ]; then
			xbacklight -set 15
		else 
			xbacklight -set 100
			notify-send "Connected to AC" "$(acpi|awk -F "," '{print $3}')"
		fi
	fi
	sleep 1
done
