#!/usr/bin/env sh

if [[ ! -f /home/ciguatera/Documents/iptables ]]; then
	echo "backup not found!"
	exit 1
fi
# Remove the iptables policys.
iptables -F
iptables -t nat -F
iptables -t mangle -F

ip6tables -F
ip6tables -t nat -F
ip6tables -t mangle -F

iptables-save
iptables-restore < /home/ciguatera/Documents/iptables
mv /home/ciguatera/Documents/iptables /home/ciguatera/Documents/lastiptables

echo "iptable restored"

exit 0
